name:                lambdatorrent
version:             0.1.0.0
github:              "juggernautjha/lambdatorrent"
license:             BSD-3-Clause
author:              "juggernautjha"
maintainer:          "juggernautjha@gmail.com"
copyright:           "2024 juggernautjha"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lambdatorrent#readme>

dependencies:
- base >= 4.7 && < 5
- base16-bytestring
- cryptohash
- uri-encode
- lens
- bytestring
- Cabal-syntax
- wreq
- HTTP
- tls
- http-client-tls
- http-client
- http-conduit
- crypton-connection
- req
- data-default-class
- data-default
- network




library:
  source-dirs: src

executables:
  lambdatorrent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdatorrent

tests:
  lambdatorrent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdatorrent
  
